#!/bin/bash

version="0.2"

usage="Usage: $0 [options] JOURNAL VOLUME NUMBER"

noclean=false
verbose=false
has_tag=false
npositional=0
root=`dirname $0`

while [ $# -gt 0 ] ; do
    case $1 in
        -h|--help) 
            cat << EOF
$usage

Options:

    --noclean    Do not remove the temporary 'cite.out' file
                 with the downloaded citation.
    --tag=TAG    Use TAG as the post-processing citation tag, rather
                 than trying to auto-generate it.
    --journals   List available journals.
    -v,--verbose Run verbosely
    --help       Print this message.
    --version    Print version information.

Examples:

    $0 prl 111 045301 >> bibliography.bib

    $0 --tag=Bugnion2013 prl 111 045301 >> bibliography.bib
EOF
            exit
            ;;
        --noclean)
            noclean=true
            ;;
        --version)
            echo $0 v$version
            exit
            ;;
        --tag=*)
            has_tag=true
            tag=${1#--tag=}
            ;;
        --tag)
            shift
            has_tag=true
            tag=$1
            ;;
        --journals)
            cat << EOF
Abbreviation  Journal
-----------   -------
pra           Physical Review A
prb           Physical Review B
prc           Physical Review C
pre           Physical Review E
prl           Physical Review L
rmp           Review of Modern Physics
pr            Physical Review
jcp           Journal of Chemical Physics
EOF
            exit
            ;;
        -v|--verbose)
            verbose=true
            ;;
        -*|--*)
            echo "Unrecognnized option: $1"
            echo "$0 --help for a list of options"
            ;;
        *)
            case $npositional in
                0)
                    journal=$1
                    ;;
                1)
                    volume=$1
                    ;;
                2)
                    number=$1
                    ;;
                *)
                    echo $usage
                    exit
                    ;;
            esac
            npositional=$((npositional+1))
            ;;
    esac
    shift
done

if [ $npositional != 3 ] ; then
    echo $usage
    exit
fi

if $verbose ; then
    echo "Journal: " $journal 1>&2
    echo "Volume:  " $volume  1>&2
    echo "Page:    " $number  1>&2
    if $has_tag ; then
        echo "Tag:     " $tag 1>&2
    else
        echo "Tag:    auto" 1>&2
    fi
fi

case $journal in
    pra|prb|prl|pre|pr|prc|rmp)
        $root/aps.sh $journal $volume $number
        ;;
    jcp)
        $root/jcp.sh $volume $number
        ;;
    *)
        echo "Journal must be one of: " 1>&2
        echo "pra, prb, pre, prl, rmp, pr or jcp" 1>&2
        exit
esac

if [ $? -ne 0 ] ; then
    echo "Download failed." 1>&2
    exit
fi

if ! $has_tag ; then
    tag=`python $root/build_tag.py cite.out`
fi

echo "New tag: " $tag 1>&2

sed -e "s/@article{.*,/@article{$tag,/"  cite.out
echo ""

rm cite.out
